#!/bin/bash
PERSON1=SASHI
PERSON2=MOUNIKA
echo "${PERSON1}::HELLO ${PERSON2} GOOD MORNING"
echo "${PERSON2}::HELLO ${PERSON1} VERY GOOD MORNING"
echo "${PERSON1}::HOW ARE YOU ${PERSON2}"
echo "${PERSON2}::IM FINE ${PERSON1}"